// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using ActivitySignUpDAL.Models.Enums;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ActivitySignUpDAL.Models
{
    public partial class Activity
    {
        public Activity()
        {
            Subscriptions = new HashSet<Subscription>();
        }

        [Key]
        public int ActivityId { get; set; }
        [Required]
        [StringLength(255)]
        [Display(Name = "Activity Name")]
        public string ActivityName { get; set; }
        [Required]
        [Range(1, int.MaxValue, ErrorMessage = "The Activity Type field is required.")]
        public ActivityTypes ActivityType { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateCreated { get; set; }
        public bool Deleted { get; set; }

        [InverseProperty(nameof(Subscription.Activity))]
        public virtual ICollection<Subscription> Subscriptions { get; set; }
    }
}