// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ActivitySignUpDAL.Models
{
    public partial class Subscription
    {
        [Key]
        public int SubscriptionId { get; set; }
        [Required]
        [StringLength(255)]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }
        [Required]
        [StringLength(255)]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }
        [Required]
        [StringLength(255)]
        [EmailAddress]
        public string Email { get; set; }
        [Required]
        [Range(1, int.MaxValue, ErrorMessage = "The Activity Type field is required.")]
        public int ActivityId { get; set; }
        public string Comments { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateCreated { get; set; }

        [ForeignKey(nameof(ActivityId))]
        [InverseProperty("Subscriptions")]
        public virtual Activity Activity { get; set; }
    }
}